name: News Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install requests

      - name: Run script
        run: python main.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
